### ISSUE TITLE
TLS support breaks cluster mode

### ISSUE THREAD

**Issue by juliangut** [farhadi/node-smpp#79]
I've been using this library for long on its version 0.2.0 but just recently I've had the need to implement an SMPP server with TLS and so updated to 0.3.1

A single instance of the server (with and without TLS) runs smoothly but to my despair it is not the case when you run several instances with PM2 on cluster mode, non-TLS instances get broken effectively making the library usable only for TLS servers when on cluste mode

```sh
TypeError: Cannot read property 'context' of undefined
    at Server.getTicketKeys (_tls_wrap.js:915:28)
    at Server._getServerData (_tls_wrap.js:904:22)
    at EventEmitter.cluster._getServer (internal/cluster/child.js:79:24)
    at listenInCluster (net.js:1409:11)
    at Server.listen (net.js:1480:7)
    at Server.listen (/home/[...]/node_modules/smpp/lib/smpp.js:176:37)
    at Object.<anonymous> (/home/[...]/server.js:234:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

I assume this functionality reduction was not meant when TLS support was added on version 0.3.0, I guess no one else has tried running several SMPP servers with and without TLS on the same machine

```yml
apps:
  - name: server
    script: ./server.js
    instances: 4
    autorestart: true
    max_restarts: 3
    min_uptime: 30000
    error_file: ~/.pm2/log/server-err.log
    out_file: ~/.pm2/log/server-out.log
    exec_mode: cluster
    kill_timeout: 5000
  - name: server-tls
    script: ./server.js
    args: tls
    instances: 2
    autorestart: true
    max_restarts: 3
    min_uptime: 30000
    error_file: ~/.pm2/log/server-tls-err.log
    out_file: ~/.pm2/log/server-tls-out.log
    exec_mode: cluster
    kill_timeout: 5000
```

The problem seems to be the [inheritance of the Server object from tls.Server](https://github.com/farhadi/node-smpp/blob/master/lib/smpp.js#L167), so changing this line solves the situation while keeping support for TLS

```node
util.inherits(Server, tls.Server);
//to
util.inherits(Server, net.Server);
```

Additionally [always listening from tls](https://github.com/farhadi/node-smpp/blob/master/lib/smpp.js#L176) doesn't look correct to me when you can decide transport the same way you do on Server creation:

```node
Server.prototype.listen = function() {
    var transport = this.tls ? tls : net;
    var args = [this.tls ? 3550 : 2775];
    if (typeof arguments[0] == 'function') {
        args[1] = arguments[0];
    } else if (arguments.length > 0) {
        args = arguments;
    }
    return transport.Server.prototype.listen.apply(this, args);
};
```

I can make a simple PR to fix this, I need this patch ASAP so I'll do it only if I can be assured it will be accepted and merged quickly, as the project really seems dead, otherwise I'll be forced to fork the project
